// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_msg_2eproto__INCLUDED
#define PROTOBUF_msg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class HHLogin;
class HHLoginDefaultTypeInternal;
extern HHLoginDefaultTypeInternal _HHLogin_default_instance_;

namespace protobuf_msg_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_msg_2eproto

enum HHLogin_eClientType {
  HHLogin_eClientType_eTx2 = 1
};
bool HHLogin_eClientType_IsValid(int value);
const HHLogin_eClientType HHLogin_eClientType_eClientType_MIN = HHLogin_eClientType_eTx2;
const HHLogin_eClientType HHLogin_eClientType_eClientType_MAX = HHLogin_eClientType_eTx2;
const int HHLogin_eClientType_eClientType_ARRAYSIZE = HHLogin_eClientType_eClientType_MAX + 1;

const ::google::protobuf::EnumDescriptor* HHLogin_eClientType_descriptor();
inline const ::std::string& HHLogin_eClientType_Name(HHLogin_eClientType value) {
  return ::google::protobuf::internal::NameOfEnum(
    HHLogin_eClientType_descriptor(), value);
}
inline bool HHLogin_eClientType_Parse(
    const ::std::string& name, HHLogin_eClientType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<HHLogin_eClientType>(
    HHLogin_eClientType_descriptor(), name, value);
}
// ===================================================================

class HHLogin : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HHLogin) */ {
 public:
  HHLogin();
  virtual ~HHLogin();

  HHLogin(const HHLogin& from);

  inline HHLogin& operator=(const HHLogin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HHLogin& default_instance();

  static inline const HHLogin* internal_default_instance() {
    return reinterpret_cast<const HHLogin*>(
               &_HHLogin_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(HHLogin* other);

  // implements Message ----------------------------------------------

  inline HHLogin* New() const PROTOBUF_FINAL { return New(NULL); }

  HHLogin* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HHLogin& from);
  void MergeFrom(const HHLogin& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HHLogin* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef HHLogin_eClientType eClientType;
  static const eClientType eTx2 =
    HHLogin_eClientType_eTx2;
  static inline bool eClientType_IsValid(int value) {
    return HHLogin_eClientType_IsValid(value);
  }
  static const eClientType eClientType_MIN =
    HHLogin_eClientType_eClientType_MIN;
  static const eClientType eClientType_MAX =
    HHLogin_eClientType_eClientType_MAX;
  static const int eClientType_ARRAYSIZE =
    HHLogin_eClientType_eClientType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  eClientType_descriptor() {
    return HHLogin_eClientType_descriptor();
  }
  static inline const ::std::string& eClientType_Name(eClientType value) {
    return HHLogin_eClientType_Name(value);
  }
  static inline bool eClientType_Parse(const ::std::string& name,
      eClientType* value) {
    return HHLogin_eClientType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required int32 port = 2;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // required int32 version = 3;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 3;
  ::google::protobuf::int32 version() const;
  void set_version(::google::protobuf::int32 value);

  // required .HHLogin.eClientType clienttype = 1;
  bool has_clienttype() const;
  void clear_clienttype();
  static const int kClienttypeFieldNumber = 1;
  ::HHLogin_eClientType clienttype() const;
  void set_clienttype(::HHLogin_eClientType value);

  // @@protoc_insertion_point(class_scope:HHLogin)
 private:
  void set_has_clienttype();
  void clear_has_clienttype();
  void set_has_port();
  void clear_has_port();
  void set_has_version();
  void clear_has_version();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::int32 version_;
  int clienttype_;
  friend struct protobuf_msg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HHLogin

// required .HHLogin.eClientType clienttype = 1;
inline bool HHLogin::has_clienttype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HHLogin::set_has_clienttype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HHLogin::clear_has_clienttype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HHLogin::clear_clienttype() {
  clienttype_ = 1;
  clear_has_clienttype();
}
inline ::HHLogin_eClientType HHLogin::clienttype() const {
  // @@protoc_insertion_point(field_get:HHLogin.clienttype)
  return static_cast< ::HHLogin_eClientType >(clienttype_);
}
inline void HHLogin::set_clienttype(::HHLogin_eClientType value) {
  assert(::HHLogin_eClientType_IsValid(value));
  set_has_clienttype();
  clienttype_ = value;
  // @@protoc_insertion_point(field_set:HHLogin.clienttype)
}

// required int32 port = 2;
inline bool HHLogin::has_port() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HHLogin::set_has_port() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HHLogin::clear_has_port() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HHLogin::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 HHLogin::port() const {
  // @@protoc_insertion_point(field_get:HHLogin.port)
  return port_;
}
inline void HHLogin::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:HHLogin.port)
}

// required int32 version = 3;
inline bool HHLogin::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HHLogin::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HHLogin::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HHLogin::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::google::protobuf::int32 HHLogin::version() const {
  // @@protoc_insertion_point(field_get:HHLogin.version)
  return version_;
}
inline void HHLogin::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:HHLogin.version)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::HHLogin_eClientType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::HHLogin_eClientType>() {
  return ::HHLogin_eClientType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2eproto__INCLUDED
